<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="1" failures="0" skipped="0" tests="1" time="0.080" timestamp="2024-04-11T11:05:06.536199" hostname="john.burke-JJ34GQ4T4N"><testcase classname="redis_enterprise" name="tests.test_redis_enterprise" time="0.000"><error message="collection failure">ImportError while importing test module '/Users/john.burke/dd/integrations-extras/redis_enterprise/tests/test_redis_enterprise.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/pathlib.py:567: in import_path
    importlib.import_module(module_name)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
&lt;frozen importlib._bootstrap&gt;:1050: in _gcd_import
    ???
&lt;frozen importlib._bootstrap&gt;:1027: in _find_and_load
    ???
&lt;frozen importlib._bootstrap&gt;:1006: in _find_and_load_unlocked
    ???
&lt;frozen importlib._bootstrap&gt;:688: in _load_unlocked
    ???
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:178: in exec_module
    exec(co, module.__dict__)
tests/test_redis_enterprise.py:8: in &lt;module&gt;
    from datadog_checks.redis_enterprise.check import RedisEnterpriseCheck
E   ModuleNotFoundError: No module named 'datadog_checks.redis_enterprise'</error></testcase></testsuite></testsuites>